application: umbrella-revolution
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Static Folder

- url: /post-service/
  static_dir: post-service/

- url: /components/
  static_dir: polymer/components/

- url: /stylesheets/
  static_dir: stylesheets/

- url: /api/
  static_dir: api/

# Scripts

- url: .*
  script: main.php

- url: .*
  script: php/main.php